import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { MdiGithub } from "~/components/Icones";
import { api } from "~/utils/api";

const ProfilePage: NextPage = () => {
  const router = useRouter();
  const { data: user } = api.user.getUserByUsername.useQuery({
    username: router.query.username as string,
  });
  const { username } = router.query;

  if (typeof username !== "string") {
    return null;
  }

  if (!user) {
    return <div>loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Code Crafers | Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section
          style={{
            clipPath: "inset(0 -100vmax)",
          }}
          className="mx-auto flex max-w-[80rem] flex-col items-center space-y-5 bg-white px-2 py-4 shadow-[0_0_0_100vmax] shadow-white md:flex-row md:space-x-8 md:space-y-0 md:px-6 md:py-8 "
        >
          <div>
            <Image
              className=" h-32 w-32 rounded-full md:h-40 md:w-40 "
              src={user.image || ""}
              alt="user"
              width={200}
              height={200}
            />
          </div>
          <div className="flex flex-[2] flex-col justify-between gap-3 ">
            <div className="flex flex-col items-center md:items-start">
              <h3 className="text-center text-2xl font-medium  text-gray-900 ">
                {user.name}
              </h3>
              <p className="  ">@{user.username}</p>
            </div>
            <Link target="_blank" href={(user.githubURL as string) || ""}>
              {user.githubURL && <MdiGithub className="h-8 w-8" />}
            </Link>
          </div>
          <p className="flex-[3]">{user.about}</p>
        </section>
      </main>
    </>
  );
};

export default ProfilePage;
