import { type NextPage } from "next";
import Head from "next/head";

const NewChallengePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Code Crafers | Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Profile page</h1>
      </main>
    </>
  );
};

export default NewChallengePage;
